conf.py:
  copyright: 2015-2017
  project: TYPO3 Frontend Editing
  version: 0.1
  release: 0.1.0
  latex_documents:
  - - Index
    - sphinx.tex
    - Sphinx Python Documentation Generator and Viewer
    - Xavier Perseguers
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}